In [2]:
import numpy as np
import pandas as pd

In [10]:
# creating numpy array from list
list1 = [2,4,6,8]
list2 = [3,6,9,12]
arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1)
arr2

[2 4 6 8]


array([ 3,  6,  9, 12])

In [8]:
# nupy 2D array from list
list2d1 = [[2,4,6,8],[3,6,9,12]]
arr2d1 = np.array(list2d1)
arr2d1

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [11]:
# shape of numpy array
arr2d1.shape

(2, 4)

In [12]:
# number of rows in 2d numpy array
arr2d1.shape[0]

2

In [13]:
# number of columns in 2d numpy array
arr2d1.shape[1]

4

In [14]:
# number of elements in a numpy array
arr2d1.size

8

In [15]:
# dimentionality of an array
arr2d1.ndim

2

In [16]:
# data type held by numpy array
arr2d1.dtype

dtype('int32')

In [17]:
# creating numpy array with initial elements as zero
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# creating numpy array with initial element as k
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [20]:
# creating numpy array with random elements
np.random.random((2,3))

array([[0.58023723, 0.74368866, 0.46303944],
       [0.79689945, 0.33191042, 0.95486338]])

In [21]:
# create array of values in a range at given difference
np.arange(10,80,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [24]:
# create k linearly spaced values in a given range
np.linspace(5,6,4)

array([5.        , 5.33333333, 5.66666667, 6.        ])

In [25]:
# print sum of all elements of the array
np.sum(arr1)

20

In [26]:
# prints sum of the array row-wise
np.sum(arr2d1, axis=1)

array([20, 30])

In [27]:
# print sum of the array column-wise
np.sum(arr2d1, axis=0)

array([ 5, 10, 15, 20])

In [28]:
# divide array elements index wise
np.divide(arr1, arr2)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])

In [29]:
# multiply array elements index wise 
np.multiply(arr1, arr2)

array([ 6, 24, 54, 96])

In [30]:
# print log of numpy array
np.log(arr2d1)

array([[0.69314718, 1.38629436, 1.79175947, 2.07944154],
       [1.09861229, 1.79175947, 2.19722458, 2.48490665]])

In [31]:
# print sin of numpy array
np.sin(arr2d1)

array([[ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825],
       [ 0.14112001, -0.2794155 ,  0.41211849, -0.53657292]])

In [32]:
# print cos of numpy array
np.cos(arr2d1)

array([[-0.41614684, -0.65364362,  0.96017029, -0.14550003],
       [-0.9899925 ,  0.96017029, -0.91113026,  0.84385396]])

In [33]:
# compare elements of two array
np.equal([2,3,5,7],[2,5,7,7])

array([ True, False, False,  True])

In [34]:
# compare two arrays
np.array_equal([2,3,4,7],[2,3,4,7])

True

### Aggregations

In [36]:
arr2d1

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [37]:
np.sum(arr2d1)

50

In [38]:
np.min(arr2d1)

2

In [39]:
np.max(arr2d1)

12

In [40]:
np.mean(arr2d1)

6.25

In [41]:
np.mean(arr2d1, axis=0)

array([ 2.5,  5. ,  7.5, 10. ])

In [42]:
np.mean(arr2d1, axis=1)

array([5. , 7.5])

In [43]:
np.std(arr2d1)

3.112474899497183

In [44]:
np.median(arr2d1)

6.0

In [45]:
np.corrcoef(arr2d1)

array([[1., 1.],
       [1., 1.]])

In [46]:
np.corrcoef(arr1)

1.0